// The mass-generation console (SOMET-538).
//
// One table over every art subject -- tiles, entities, items, class skills and
// passive-tree labels, ~1000 rows -- with the filters and selection needed to
// drive a batch measured in hours.
//
// EVERY RULE LIVES IN artSelection.js and is unit-tested there; this file
// renders them and owns no logic of its own. That split is the same one
// PassiveNodesAdmin uses, and for the same reason: the interesting failures
// here are selection arithmetic, not markup.
//
// PROGRESS COMES FROM THE CATALOG. The coverage line counts rows that actually
// have art rather than a counter incremented as jobs finish -- a counter drifts
// from reality the moment anything fails, restarts, or is generated by another
// route, and this batch does all three.
import { useMemo, useState } from 'react';
import styled from 'styled-components';
import {
  useArtSubjects, useArtQueue, useEnqueueArt, useStartArtBatch, useStopArtBatch,
  useRequeueStale,
} from './useArtConsole.js';
import { useAiProviders } from './useAiProviders.js';
import { assetUrlVersioned } from './useTileSprites.js';
import {
  sortSubjects, applyFilters, clampPage, pageCount, toggle, selectPage, deselectPage,
  isPageFullySelected, selectAllMatching, selectAllLabel, byKind, subjectId,
  enqueueSummary, coverage, selectionOutsideFilter, PAGE_SIZE,
} from './artSelection.js';

const Wrap = styled.div`color: var(--s2-text);`;
const Bar = styled.div`
  display: flex; gap: 0.75rem; flex-wrap: wrap; align-items: flex-end; margin-bottom: 0.75rem;
`;
const Field = styled.label`
  display: flex; flex-direction: column; gap: 0.25rem;
  font-size: 0.8rem; color: var(--s2-text-muted);
  input, select {
    background: var(--s2-bg-sunken); color: var(--s2-text);
    border: 1px solid var(--s2-border-strong); border-radius: 4px;
    padding: 0.4rem; min-width: 140px; font-size: 0.9rem;
  }
`;
const Button = styled.button`
  background: var(--s2-accent); color: var(--s2-on-accent); border: none; border-radius: 6px;
  padding: 0.4rem 0.9rem; font-weight: bold; cursor: pointer; font-size: 0.85rem;
  &:disabled { opacity: 0.5; cursor: default; }
`;
const Secondary = styled(Button)`background: var(--s2-btn-grey);`;
const Hint = styled.p`color: var(--s2-text-muted); font-size: 0.85rem; margin: 0.25rem 0;`;
const Err = styled.p`color: var(--s2-danger); font-size: 0.85rem; margin: 0.25rem 0;`;
const TableWrap = styled.div`
  overflow-x: auto; border: 1px solid var(--s2-border); border-radius: 8px;
  background: var(--s2-surface-raised);
`;
const Table = styled.table`
  width: 100%; border-collapse: collapse; font-size: 0.85rem;
  th, td { text-align: left; padding: 0.35rem 0.6rem; border-bottom: 1px solid var(--s2-border); }
  th { color: var(--s2-text-muted); font-weight: normal; }
  tbody tr:hover { background: var(--s2-overlay); }
`;
const Thumb = styled.div`
  width: 32px; height: 32px; border-radius: 4px; background: var(--s2-bg-sunken);
  background-size: cover; background-position: center;
  border: 1px solid var(--s2-border);
`;
const Pager = styled.div`display: flex; gap: 0.5rem; align-items: center; margin: 0.75rem 0;`;
const Pill = styled.span`
  font-size: 0.75rem; padding: 0.1rem 0.4rem; border-radius: 999px;
  background: var(--s2-bg-sunken); color: var(--s2-text-muted);
`;
const Fail = styled(Pill)`color: var(--s2-danger);`;
const Mono = styled.td`font-family: ui-monospace, SFMono-Regular, Menlo, monospace;`;

function ArtConsoleAdmin() {
  const { kinds, subjects, isLoadingSubjects, subjectsError } = useArtSubjects();
  const { stats, run } = useArtQueue();
  const { providers, activeProvider } = useAiProviders();
  const enqueue = useEnqueueArt();
  const startBatch = useStartArtBatch();
  const stopBatch = useStopArtBatch();
  const requeue = useRequeueStale();

  const [kind, setKind] = useState('all');
  const [art, setArt] = useState('missing');   // the resume filter, by default
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState(new Set());
  const [backend, setBackend] = useState('connector');
  const [providerId, setProviderId] = useState('');
  const [notice, setNotice] = useState(null);
  const [failure, setFailure] = useState(null);

  const matching = useMemo(
    () => sortSubjects(applyFilters(subjects, { kind, art, search })),
    [subjects, kind, art, search],
  );
  const shownPage = clampPage(page, matching.length);
  const pageRows = matching.slice((shownPage - 1) * PAGE_SIZE, shownPage * PAGE_SIZE);
  const cover = coverage(subjects);
  const allLabel = selectAllLabel(matching.length, pageRows.length);
  const hiddenSelected = selectionOutsideFilter(selected, matching);

  const onEnqueue = async () => {
    const grouped = byKind(selected);
    if (grouped.size === 0) return;
    setFailure(null);
    // CAUGHT, not left to reject. mutateAsync rethrows after the hook's
    // onError toast, and an uncaught rejection here showed the admin nothing
    // at all when the request 400'd -- the button simply did not work. Found
    // in the browser.
    try {
      const results = await enqueue.mutateAsync({
        byKind: grouped,
        backend,
        providerId: backend === 'connector' && providerId ? Number(providerId) : null,
      });
      // Reported rather than assumed: enqueue is idempotent, so "100 selected,
      // 3 queued" is a normal outcome and needs its breakdown to make sense.
      setNotice(enqueueSummary(results).message);
      setSelected(new Set());
    } catch (err) {
      // The hook has already toasted; keep it on screen too, because a batch
      // that silently did not start is the worst outcome here.
      setNotice(null);
      setFailure(err.message);
    }
  };

  if (subjectsError) return <Err>{String(subjectsError.message)}</Err>;

  return (
    <Wrap>
      <h2>Art generation</h2>
      <Hint>
        {isLoadingSubjects ? 'Loading the catalogue…' : (
          <>
            {cover.withArt} of {cover.total} subjects have art
            {cover.missing > 0 && <> · {cover.missing} missing</>}
            {cover.failed > 0 && <> · {cover.failed} failed</>}
            {stats && <> · queue: {stats.queued || 0} queued, {stats.running || 0} running, {stats.failed || 0} failed</>}
          </>
        )}
      </Hint>

      <Bar>
        <Field>
          Kind
          <select value={kind} onChange={(e) => { setKind(e.target.value); setPage(1); }}>
            <option value="all">All kinds</option>
            {kinds.map((k) => <option key={k} value={k}>{k}</option>)}
          </select>
        </Field>
        <Field>
          Art
          <select value={art} onChange={(e) => { setArt(e.target.value); setPage(1); }}>
            <option value="missing">Missing art</option>
            <option value="has">Has art</option>
            <option value="failed">Last job failed</option>
            <option value="all">Any</option>
          </select>
        </Field>
        <Field>
          Search
          <input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }}
            placeholder="name or key" />
        </Field>
        <Field>
          Backend
          <select value={backend} onChange={(e) => setBackend(e.target.value)}>
            <option value="connector">AI connector</option>
            <option value="local">Local sprite-gen</option>
          </select>
        </Field>
        {backend === 'connector' && (
          <Field>
            Provider
            <select value={providerId} onChange={(e) => setProviderId(e.target.value)}>
              <option value="">(the active provider)</option>
              {(providers || []).map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
          </Field>
        )}
      </Bar>

      <Bar>
        <Button onClick={onEnqueue} disabled={selected.size === 0 || enqueue.isPending}>
          Queue {selected.size} selected
        </Button>
        {allLabel && (
          <Secondary onClick={() => setSelected(selectAllMatching(matching))}>{allLabel}</Secondary>
        )}
        {selected.size > 0 && (
          <Secondary onClick={() => setSelected(new Set())}>Clear selection</Secondary>
        )}
        <Button
          onClick={() => startBatch.mutate({
            provider_id: providerId ? Number(providerId) : activeProvider?.id,
            concurrency: 1,
          })}
          disabled={run?.running || !(providerId || activeProvider)}
          title={!(providerId || activeProvider)
            ? 'Choose a provider, or set an active one in AI Providers'
            : undefined}
        >
          {run?.running ? 'Running…' : 'Start batch'}
        </Button>
        {run?.running && <Secondary onClick={() => stopBatch.mutate()}>Stop</Secondary>}
        <Secondary onClick={() => requeue.mutate()}>Rescue stranded jobs</Secondary>
      </Bar>

      {/* Selection survives a filter change on purpose, but silently doing so
          means the button can read "Queue 100 selected" with none of them on
          screen. Stated rather than cleared. */}
      {hiddenSelected > 0 && (
        <Hint>
          {hiddenSelected} of the {selected.size} selected are not shown by this filter.
          {' '}<button type="button" onClick={() => setSelected(new Set())}
            style={{ background: 'none', border: 'none', color: 'var(--s2-accent)',
              cursor: 'pointer', padding: 0, font: 'inherit', textDecoration: 'underline' }}>
            Clear selection
          </button>
        </Hint>
      )}
      {notice && <Hint>{notice}</Hint>}
      {failure && <Err>{failure}</Err>}
      {run?.error && <Err>Batch stopped: {run.error}</Err>}

      <TableWrap>
        <Table>
          <thead>
            <tr>
              <th>
                <input
                  type="checkbox"
                  aria-label="Select this page"
                  checked={isPageFullySelected(selected, pageRows)}
                  onChange={(e) => setSelected(
                    e.target.checked ? selectPage(selected, pageRows)
                      : deselectPage(selected, pageRows),
                  )}
                />
              </th>
              <th>Art</th><th>Kind</th><th>Key</th><th>Status</th><th>Updated</th>
            </tr>
          </thead>
          <tbody>
            {pageRows.map((s) => {
              const id = subjectId(s);
              return (
                <tr key={id}>
                  <td>
                    <input
                      type="checkbox"
                      aria-label={`Select ${id}`}
                      checked={selected.has(id)}
                      onChange={() => setSelected(toggle(selected, id))}
                    />
                  </td>
                  <td>
                    <Thumb style={s.image
                      ? { backgroundImage: `url(${assetUrlVersioned(s.image, s.updated_at)})` }
                      : undefined} />
                  </td>
                  <td><Pill>{s.kind}</Pill></td>
                  <Mono title={s.base_prompt}>{s.key}</Mono>
                  <td>
                    {/* A FAILED subject stays visible WITH ITS REASON rather
                        than merely being absent from the missing-art page. */}
                    {s.job_state === 'failed'
                      ? <Fail title={s.job_error || ''}>failed</Fail>
                      : s.job_state ? <Pill>{s.job_state}</Pill> : null}
                    {s.render_mode === 'rect' && <Pill title="draws as a colour box"> rect</Pill>}
                  </td>
                  <td>{s.updated_at ? String(s.updated_at).slice(0, 10) : '—'}</td>
                </tr>
              );
            })}
            {pageRows.length === 0 && !isLoadingSubjects && (
              <tr><td colSpan={6}><Hint>Nothing matches this filter.</Hint></td></tr>
            )}
          </tbody>
        </Table>
      </TableWrap>

      <Pager>
        <Secondary onClick={() => setPage(shownPage - 1)} disabled={shownPage <= 1}>Prev</Secondary>
        <span>Page {shownPage} of {pageCount(matching.length)} · {matching.length} matching</span>
        <Secondary
          onClick={() => setPage(shownPage + 1)}
          disabled={shownPage >= pageCount(matching.length)}
        >Next</Secondary>
      </Pager>
    </Wrap>
  );
}

export default ArtConsoleAdmin;
