// The mass-generation console (SOMET-538).
//
// One table over every art subject -- tiles, entities, items, class skills and
// passive-tree labels, ~1000 rows -- with the filters and selection needed to
// drive a batch measured in hours.
//
// EVERY RULE LIVES IN artSelection.js and is unit-tested there; this file
// renders them and owns no logic of its own. That split is the same one
// PassiveNodesAdmin uses, and for the same reason: the interesting failures
// here are selection arithmetic, not markup.
//
// PROGRESS COMES FROM THE CATALOG. The coverage line counts rows that actually
// have art rather than a counter incremented as jobs finish -- a counter drifts
// from reality the moment anything fails, restarts, or is generated by another
// route, and this batch does all three.
import { useMemo, useState } from 'react';
import styled from 'styled-components';
import {
  useArtSubjects, useArtQueue, useEnqueueArt, useStartArtBatch, useStopArtBatch,
  useRequeueStale, useRequeueFailures, useArtHistory,
} from './useArtConsole.js';
import { useAiProviders } from './useAiProviders.js';
import { assetUrlVersioned } from './useTileSprites.js';
import {
  sortSubjects, freezeOrder, applyFilters, clampPage, pageCount, toggle, selectPage, deselectPage,
  isPageFullySelected, selectAllMatching, selectAllLabel, byKind, subjectId,
  enqueueSummary, coverage, selectionOutsideFilter, PAGE_SIZE,
} from './artSelection.js';

// The house admin-root style, shared verbatim with the eight other admin
// panels. Load-bearing rather than cosmetic: GameShell's ContentArea is
// `overflow: hidden`, so a root without `height: 100%; overflow-y: auto` is
// CLIPPED -- ~80 of the 100 rows and the pager under them were unreachable,
// with no scrollbar to say so. This element is also the scrollport the sticky
// header below anchors to.
// Shared with the sticky header's offset below; see the comment there for why
// the two must stay equal.
const PANEL_PAD = '2rem';
const Wrap = styled.div`
  padding: ${PANEL_PAD}; color: var(--s2-text); max-width: 1200px; margin: 0 auto;
  height: 100%; overflow-y: auto; background-color: var(--s2-surface);
`;
const Bar = styled.div`
  display: flex; gap: 0.75rem; flex-wrap: wrap; align-items: flex-end; margin-bottom: 0.75rem;
`;
const Field = styled.label`
  display: flex; flex-direction: column; gap: 0.25rem;
  font-size: 0.8rem; color: var(--s2-text-muted);
  input, select {
    background: var(--s2-bg-sunken); color: var(--s2-text);
    border: 1px solid var(--s2-border-strong); border-radius: 4px;
    padding: 0.4rem; min-width: 140px; font-size: 0.9rem;
  }
`;
const Button = styled.button`
  background: var(--s2-accent); color: var(--s2-on-accent); border: none; border-radius: 6px;
  padding: 0.4rem 0.9rem; font-weight: bold; cursor: pointer; font-size: 0.85rem;
  &:disabled { opacity: 0.5; cursor: default; }
`;
const Secondary = styled(Button)`background: var(--s2-btn-grey);`;
const Hint = styled.p`color: var(--s2-text-muted); font-size: 0.85rem; margin: 0.25rem 0;`;
const Err = styled.p`color: var(--s2-danger); font-size: 0.85rem; margin: 0.25rem 0;`;
// DELIBERATELY not a scroll container. `overflow-x: auto` here computed
// overflow-y to `auto` as well, which made this the nearest scrollport -- the
// sticky header then pinned to THIS box (which never scrolls vertically) and
// slid away with the page. Wrap's `overflow-y: auto` already scrolls both
// axes, so nothing is lost by dropping it.
const TableWrap = styled.div`
  border: 1px solid var(--s2-border); border-radius: 8px;
  background: var(--s2-surface-raised);
`;
const Table = styled.table`
  width: 100%; border-collapse: collapse; font-size: 0.85rem;
  th, td { text-align: left; padding: 0.35rem 0.6rem; border-bottom: 1px solid var(--s2-border); }
  /* Held at the top of Wrap's scroll while 100 rows pass under it -- the
     column names and the select-this-page checkbox both stay usable.
     border-collapse:collapse gives the header's bottom border to the TABLE
     rather than the cell, and a collapsed border does not travel with a
     sticky cell, so the rule is redrawn as an inset shadow. The opaque
     background is required too: without it the rows show through.

     top is NEGATIVE PANEL_PAD, not 0. Scrolled content passes through a
     scroll container's own padding band, so a top of 0 -- which pins the header
     to the CONTENT box -- left a 2rem strip above it where half a row bled
     through in the live page. Pinning at -PANEL_PAD puts the header on the
     panel's border-box edge, where the scrollport clips instead. */
  th {
    color: var(--s2-text-muted); font-weight: normal;
    position: sticky; top: -${PANEL_PAD}; z-index: 1;
    background: var(--s2-surface-raised);
    border-bottom: none; box-shadow: inset 0 -1px 0 var(--s2-border);
  }
  tbody tr:hover { background: var(--s2-overlay); }
`;
const Thumb = styled.div`
  width: 32px; height: 32px; border-radius: 4px; background: var(--s2-bg-sunken);
  background-size: cover; background-position: center;
  border: 1px solid var(--s2-border);
`;
const Pager = styled.div`display: flex; gap: 0.5rem; align-items: center; margin: 0.75rem 0;`;
const Pill = styled.span`
  font-size: 0.75rem; padding: 0.1rem 0.4rem; border-radius: 999px;
  background: var(--s2-bg-sunken); color: var(--s2-text-muted);
`;
const Fail = styled(Pill)`color: var(--s2-danger);`;
const Mono = styled.td`font-family: ui-monospace, SFMono-Regular, Menlo, monospace;`;

// Failures grouped BY CAUSE, above the table.
//
// The table already showed a red pill per row, which answers "did this fail"
// but not "is this 68 subjects hit by one GPU fault that will clear itself, or
// one subject that needs a decision". Those need opposite responses, and the
// per-row view made the difference invisible: it read as 69 identical
// problems. Reading order is set by the server (most-actionable first).
const Failures = styled.section`
  border: 1px solid var(--s2-border); border-radius: 8px;
  background: var(--s2-surface-raised); padding: 0.75rem 1rem; margin: 0.75rem 0;
`;
const FailGroup = styled.div`
  & + & { border-top: 1px solid var(--s2-border); margin-top: 0.75rem; padding-top: 0.75rem; }
  h4 { margin: 0 0 0.2rem; font-size: 0.95rem; color: var(--s2-text); }
  p  { margin: 0 0 0.4rem; font-size: 0.85rem; color: var(--s2-text-muted); }
  code {
    display: block; font-size: 0.75rem; color: var(--s2-text-dim);
    background: var(--s2-bg-sunken); border-radius: 4px; padding: 0.35rem 0.5rem;
    margin-bottom: 0.5rem; overflow-x: auto; white-space: pre-wrap; word-break: break-word;
  }
`;
// Clickable column headers. A plain <th> gives no affordance, and this table
// has six columns of which only three are sortable.
const SortTh = styled.th`
  cursor: pointer; user-select: none;
  &:hover { color: var(--s2-text); }
  span { opacity: 0.6; margin-left: 0.25rem; }
`;

// The preview. Reuses GameShell's help-modal shape so it reads as the same
// application rather than a bolted-on lightbox.
const Backdrop = styled.div`
  position: fixed; inset: 0; z-index: 500; background: var(--s2-scrim);
  display: flex; align-items: center; justify-content: center; padding: 2rem;
`;
const Preview = styled.div`
  background: var(--s2-surface); border: 1px solid var(--s2-border); border-radius: 10px;
  padding: 1rem 1.25rem; max-width: min(900px, 92vw); max-height: 90vh; overflow-y: auto;
  box-shadow: 0 10px 40px var(--s2-scrim-soft); position: relative;
  h3 { margin: 0 0 0.5rem; color: var(--s2-text-strong); font-size: 1.15rem; }
  dl { display: grid; grid-template-columns: max-content 1fr; gap: 0.25rem 0.75rem; margin: 0.75rem 0 0; }
  dt { color: var(--s2-text-muted); font-size: 0.8rem; }
  dd { margin: 0; font-size: 0.85rem; word-break: break-word; }
`;
// THE CHECKERBOARD IS THE POINT, not decoration. Every failure this console
// keeps hitting is a transparency failure -- a subject the cutout ate, or a
// backdrop it never keyed out. Both look perfectly fine against a flat dark
// card and are obvious the moment there is a checker behind them.
const Checker = styled.div`
  --sq: 12px;
  background-color: var(--s2-bg-sunken);
  background-image:
    linear-gradient(45deg, var(--s2-overlay) 25%, transparent 25%, transparent 75%, var(--s2-overlay) 75%),
    linear-gradient(45deg, var(--s2-overlay) 25%, transparent 25%, transparent 75%, var(--s2-overlay) 75%);
  background-size: calc(var(--sq) * 2) calc(var(--sq) * 2);
  background-position: 0 0, var(--sq) var(--sq);
  border: 1px solid var(--s2-border); border-radius: 6px;
  display: flex; align-items: center; justify-content: center;
  img { max-width: 100%; max-height: 60vh; display: block; image-rendering: pixelated; }
`;
const Close = styled.button`
  position: absolute; top: 8px; right: 10px; background: none; border: none;
  color: var(--s2-text-muted); font-size: 1.4rem; line-height: 1; cursor: pointer;
  &:hover { color: var(--s2-text); }
`;
// The generation history, inside the preview.
const History = styled.div`
  margin-top: 1rem; border-top: 1px solid var(--s2-border); padding-top: 0.75rem;
  h4 { margin: 0 0 0.5rem; font-size: 0.9rem; color: var(--s2-text); }
  ol { list-style: none; margin: 0; padding: 0; }
  li { border-bottom: 1px solid var(--s2-border); padding: 0.5rem 0; font-size: 0.8rem; }
  li:last-child { border-bottom: none; }
  code {
    display: block; margin-top: 0.25rem; font-size: 0.72rem; color: var(--s2-text-dim);
    background: var(--s2-bg-sunken); border-radius: 4px; padding: 0.3rem 0.45rem;
    white-space: pre-wrap; word-break: break-word;
  }
`;
const Outcome = styled.span`
  font-size: 0.7rem; padding: 0.05rem 0.4rem; border-radius: 999px; margin-right: 0.4rem;
  background: var(--s2-bg-sunken);
  color: ${(p) => (p.$ok ? 'var(--s2-text-muted)' : 'var(--s2-danger)')};
`;

const ThumbButton = styled.button`
  background: none; border: none; padding: 0; cursor: zoom-in; display: block;
`;

const Subjects = styled.p`
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.75rem !important;
`;

function ArtConsoleAdmin() {
  const { kinds, subjects, isLoadingSubjects, subjectsError } = useArtSubjects();
  const { stats, run, failures } = useArtQueue();
  const { providers, activeProvider } = useAiProviders();
  const enqueue = useEnqueueArt();
  const startBatch = useStartArtBatch();
  const stopBatch = useStopArtBatch();
  const requeue = useRequeueStale();
  const requeueFailures = useRequeueFailures();

  const [kind, setKind] = useState('all');
  const [art, setArt] = useState('missing');   // the resume filter, by default
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState(new Set());
  const [backend, setBackend] = useState('connector');
  const [providerId, setProviderId] = useState('');
  const [notice, setNotice] = useState(null);
  const [failure, setFailure] = useState(null);
  const [sort, setSort] = useState({ by: 'subject', dir: 'asc' });
  const [preview, setPreview] = useState(null);
  const { history, isLoadingHistory } = useArtHistory(preview);

  // The frozen order, held only while a batch is running and the table is
  // sorted by a MOVING column. Without it every landed generation reshuffles
  // the page under the admin's cursor: selection itself is safe (it is keyed by
  // subjectId, not by row index) but "select this page" would mean something
  // different from one second to the next.
  //
  // A MEMO with a narrow dependency list, which is precisely the semantics
  // wanted: recapture when the batch starts/stops or the sort changes, and at
  // no other time. Two shapes were tried and rejected -- a ref read and written
  // during render (React may not replay it), and state set inside an effect
  // (cascading renders). Both were caught by the linter, and both were worse
  // than saying "this value is derived, but only from these inputs".
  const running = Boolean(run?.running);
  const frozenOrder = useMemo(
    () => (running && sort.by === 'updated'
      ? sortSubjects(applyFilters(subjects, { kind, art, search }), sort).map(subjectId)
      : null),
    // `subjects` is deliberately absent: re-capturing whenever a generation
    // lands would defeat the freeze this exists to provide. The closure reads
    // whatever `subjects` held at capture time, which is the intent.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [running, sort.by, sort.dir],
  );

  const matching = useMemo(() => {
    const filtered = applyFilters(subjects, { kind, art, search });
    if (sort.by !== 'updated') return sortSubjects(filtered, sort);
    // Hold the captured order while a batch runs; sort live otherwise.
    if (running && frozenOrder) return freezeOrder(filtered, frozenOrder);
    return sortSubjects(filtered, sort);
  }, [subjects, kind, art, search, sort, running, frozenOrder]);

  // Clicking the active column flips direction; a new column starts newest-first
  // for dates and A-Z for names, which is what each is usually wanted for.
  const sortBy = (by) => setSort((prev) => (
    prev.by === by
      ? { by, dir: prev.dir === 'asc' ? 'desc' : 'asc' }
      : { by, dir: by === 'updated' ? 'desc' : 'asc' }
  ));
  const arrow = (by) => (sort.by === by ? <span>{sort.dir === 'asc' ? '\u2191' : '\u2193'}</span> : null);
  const shownPage = clampPage(page, matching.length);
  const pageRows = matching.slice((shownPage - 1) * PAGE_SIZE, shownPage * PAGE_SIZE);
  const cover = coverage(subjects);
  const allLabel = selectAllLabel(matching.length, pageRows.length);
  const hiddenSelected = selectionOutsideFilter(selected, matching);

  // Rendered BOTH above and below the table. At PAGE_SIZE 100 the bottom copy
  // sits ~4000px down, so paging with only that one means scrolling the whole
  // page to reach the button and scrolling back up to read the result.
  const pager = (
    <Pager>
      <Secondary onClick={() => setPage(shownPage - 1)} disabled={shownPage <= 1}>Prev</Secondary>
      <span>Page {shownPage} of {pageCount(matching.length)} · {matching.length} matching</span>
      <Secondary
        onClick={() => setPage(shownPage + 1)}
        disabled={shownPage >= pageCount(matching.length)}
      >Next</Secondary>
    </Pager>
  );

  const onEnqueue = async () => {
    const grouped = byKind(selected);
    if (grouped.size === 0) return;
    setFailure(null);
    // CAUGHT, not left to reject. mutateAsync rethrows after the hook's
    // onError toast, and an uncaught rejection here showed the admin nothing
    // at all when the request 400'd -- the button simply did not work. Found
    // in the browser.
    try {
      const results = await enqueue.mutateAsync({
        byKind: grouped,
        backend,
        providerId: backend === 'connector' && providerId ? Number(providerId) : null,
      });
      // Reported rather than assumed: enqueue is idempotent, so "100 selected,
      // 3 queued" is a normal outcome and needs its breakdown to make sense.
      setNotice(enqueueSummary(results).message);
      setSelected(new Set());
    } catch (err) {
      // The hook has already toasted; keep it on screen too, because a batch
      // that silently did not start is the worst outcome here.
      setNotice(null);
      setFailure(err.message);
    }
  };

  if (subjectsError) return <Err>{String(subjectsError.message)}</Err>;

  return (
    <Wrap>
      <h2>Art generation</h2>
      <Hint>
        {isLoadingSubjects ? 'Loading the catalogue…' : (
          <>
            {cover.withArt} of {cover.total} subjects have art
            {cover.missing > 0 && <> · {cover.missing} missing</>}
            {cover.failed > 0 && <> · {cover.failed} failed</>}
            {stats && <> · queue: {stats.queued || 0} queued, {stats.running || 0} running, {stats.failed || 0} failed</>}
          </>
        )}
      </Hint>

      <Bar>
        <Field>
          Kind
          <select value={kind} onChange={(e) => { setKind(e.target.value); setPage(1); }}>
            <option value="all">All kinds</option>
            {kinds.map((k) => <option key={k} value={k}>{k}</option>)}
          </select>
        </Field>
        <Field>
          Art
          <select value={art} onChange={(e) => { setArt(e.target.value); setPage(1); }}>
            <option value="missing">Missing art</option>
            <option value="has">Has art</option>
            <option value="failed">Last job failed</option>
            <option value="all">Any</option>
          </select>
        </Field>
        <Field>
          Search
          <input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }}
            placeholder="name or key" />
        </Field>
        <Field>
          Backend
          <select value={backend} onChange={(e) => setBackend(e.target.value)}>
            <option value="connector">AI connector</option>
            <option value="local">Local sprite-gen</option>
          </select>
        </Field>
        {backend === 'connector' && (
          <Field>
            Provider
            <select value={providerId} onChange={(e) => setProviderId(e.target.value)}>
              <option value="">(the active provider)</option>
              {(providers || []).map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
            </select>
          </Field>
        )}
      </Bar>

      <Bar>
        <Button onClick={onEnqueue} disabled={selected.size === 0 || enqueue.isPending}>
          Queue {selected.size} selected
        </Button>
        {allLabel && (
          <Secondary onClick={() => setSelected(selectAllMatching(matching))}>{allLabel}</Secondary>
        )}
        {selected.size > 0 && (
          <Secondary onClick={() => setSelected(new Set())}>Clear selection</Secondary>
        )}
        <Button
          onClick={() => startBatch.mutate({
            provider_id: providerId ? Number(providerId) : activeProvider?.id,
            concurrency: 1,
          })}
          disabled={run?.running || !(providerId || activeProvider)}
          title={!(providerId || activeProvider)
            ? 'Choose a provider, or set an active one in AI Providers'
            : undefined}
        >
          {run?.running ? 'Running…' : 'Start batch'}
        </Button>
        {run?.running && <Secondary onClick={() => stopBatch.mutate()}>Stop</Secondary>}
        <Secondary onClick={() => requeue.mutate()}>Rescue stranded jobs</Secondary>
      </Bar>

      {/* Selection survives a filter change on purpose, but silently doing so
          means the button can read "Queue 100 selected" with none of them on
          screen. Stated rather than cleared. */}
      {hiddenSelected > 0 && (
        <Hint>
          {hiddenSelected} of the {selected.size} selected are not shown by this filter.
          {' '}<button type="button" onClick={() => setSelected(new Set())}
            style={{ background: 'none', border: 'none', color: 'var(--s2-accent)',
              cursor: 'pointer', padding: 0, font: 'inherit', textDecoration: 'underline' }}>
            Clear selection
          </button>
        </Hint>
      )}
      {notice && <Hint>{notice}</Hint>}
      {failure && <Err>{failure}</Err>}
      {run?.error && <Err>Batch stopped: {run.error}</Err>}

      {failures.length > 0 && (
        <Failures>
          <strong>Failed subjects, by cause</strong>
          {failures.map((g) => (
            <FailGroup key={g.kind}>
              <h4>{g.label} · {g.count}</h4>
              <p>{g.detail}</p>
              {/* The provider's OWN words, not only our label: the label says
                  what kind of problem it is, the excerpt says what actually
                  came back, and a prompt fix needs the latter. */}
              {g.example && <code>{String(g.example).slice(0, 260)}</code>}
              <Subjects>{g.subjects.map((x) => x.key).join(', ')}
                {g.count > g.subjects.length && ` … and ${g.count - g.subjects.length} more`}
              </Subjects>
              {/* Two different buttons, never one with a flag: a plain requeue
                  of a content failure is refused by the server (409) because
                  the derived seed would reproduce the same image. */}
              {g.retryable && (
                <Secondary
                  disabled={requeueFailures.isPending}
                  onClick={() => requeueFailures.mutate({ kind: g.kind })}
                >Requeue all {g.count}</Secondary>
              )}
              {g.action === 'reseed' && (
                <Secondary
                  disabled={requeueFailures.isPending}
                  onClick={() => requeueFailures.mutate({ kind: g.kind, reseed: true })}
                >Retry {g.count} with a new seed</Secondary>
              )}
              {g.action === 'fix_config' && (
                <Hint>Change the provider under AI Providers, then requeue.</Hint>
              )}
            </FailGroup>
          ))}
        </Failures>
      )}

      {pager}

      <TableWrap>
        <Table>
          <thead>
            <tr>
              <th>
                <input
                  type="checkbox"
                  aria-label="Select this page"
                  checked={isPageFullySelected(selected, pageRows)}
                  onChange={(e) => setSelected(
                    e.target.checked ? selectPage(selected, pageRows)
                      : deselectPage(selected, pageRows),
                  )}
                />
              </th>
              <th>Art</th>
              <SortTh onClick={() => sortBy('subject')}>Kind{arrow('subject')}</SortTh>
              <th>Key</th><th>Status</th>
              <SortTh onClick={() => sortBy('updated')}>Updated{arrow('updated')}</SortTh>
            </tr>
          </thead>
          <tbody>
            {pageRows.map((s) => {
              const id = subjectId(s);
              return (
                <tr key={id}>
                  <td>
                    <input
                      type="checkbox"
                      aria-label={`Select ${id}`}
                      checked={selected.has(id)}
                      onChange={() => setSelected(toggle(selected, id))}
                    />
                  </td>
                  <td>
                    {/* Only a subject WITH art opens a preview: a button that
                        opens an empty box is worse than no button. */}
                    {s.image ? (
                      <ThumbButton
                        type="button"
                        aria-label={`Preview ${id}`}
                        onClick={() => setPreview(s)}
                      >
                        <Thumb style={{ backgroundImage: `url(${assetUrlVersioned(s.image, s.updated_at)})` }} />
                      </ThumbButton>
                    ) : <Thumb />}
                  </td>
                  <td><Pill>{s.kind}</Pill></td>
                  <Mono title={s.base_prompt}>{s.key}</Mono>
                  <td>
                    {/* A FAILED subject stays visible WITH ITS REASON rather
                        than merely being absent from the missing-art page. */}
                    {s.job_state === 'failed'
                      ? <Fail title={s.job_error || ''}>failed</Fail>
                      : s.job_state ? <Pill>{s.job_state}</Pill> : null}
                    {s.render_mode === 'rect' && <Pill title="draws as a colour box"> rect</Pill>}
                  </td>
                  <td>{s.updated_at ? String(s.updated_at).slice(0, 10) : '—'}</td>
                </tr>
              );
            })}
            {pageRows.length === 0 && !isLoadingSubjects && (
              <tr><td colSpan={6}><Hint>Nothing matches this filter.</Hint></td></tr>
            )}
          </tbody>
        </Table>
      </TableWrap>

      {pager}

      {preview && (
        <Backdrop
          onClick={() => setPreview(null)}
          onKeyDown={(e) => { if (e.key === 'Escape') setPreview(null); }}
          role="presentation"
        >
          <Preview onClick={(e) => e.stopPropagation()}>
            <Close type="button" aria-label="Close preview" onClick={() => setPreview(null)}>×</Close>
            <h3>{preview.key}</h3>
            <Checker>
              <img
                src={assetUrlVersioned(preview.image, preview.updated_at)}
                alt={preview.key}
              />
            </Checker>
            <dl>
              <dt>Kind</dt><dd>{preview.kind}</dd>
              <dt>Updated</dt><dd>{preview.updated_at ? String(preview.updated_at).slice(0, 19).replace('T', ' ') : '—'}</dd>
              {preview.render_mode && <><dt>Render</dt><dd>{preview.render_mode}</dd></>}
              {preview.job_state && <><dt>Job</dt><dd>{preview.job_state}</dd></>}
              {/* The prompt is what to change when the picture is wrong, so it
                  is shown in full rather than truncated into a tooltip. */}
              {preview.base_prompt && <><dt>Prompt</dt><dd>{preview.base_prompt}</dd></>}
              {preview.job_error && <><dt>Error</dt><dd>{preview.job_error}</dd></>}
            </dl>

            <History>
              <h4>Generation history</h4>
              {isLoadingHistory && <Hint>Loading…</Hint>}
              {!isLoadingHistory && history.length === 0 && (
                <Hint>
                  Nothing recorded. History began on 2026-09-05; images made
                  before that carry no record of what produced them.
                </Hint>
              )}
              <ol>
                {history.map((h) => (
                  <li key={h.id}>
                    <Outcome $ok={h.outcome === 'done'}>{h.outcome}</Outcome>
                    {String(h.created_at).slice(0, 19).replace('T', ' ')}
                    {h.seed != null && <> · seed {h.seed}</>}
                    {h.params?.width && <> · {h.params.width}px</>}
                    {h.model && <> · {h.model}</>}
                    {/* The prompt VERBATIM. It is the reason this table exists:
                        after a backdrop or prompt change, this is the only way
                        to know what an image was actually asked for. */}
                    {h.composed_prompt && <code>{h.composed_prompt}</code>}
                    {h.error && <code>{h.error}</code>}
                  </li>
                ))}
              </ol>
            </History>
          </Preview>
        </Backdrop>
      )}
    </Wrap>
  );
}

export default ArtConsoleAdmin;
