const test = require('node:test');
const assert = require('node:assert');
const { Client } = require('pg');
const MigrationBuilder = require('node-pg-migrate/dist/migration-builder').default;
const migStoneType = require('../migrations/1714440165000_stone_item_type.js');
const migStoneInstances = require('../migrations/1714440166000_stone_instances.js');
const mig = require('../migrations/1714440167000_convert_magic_weapons_to_stones.js');

// This branch's schema migrations (Task 1: 1714440165000/1714440166000 --
// the 'stone' item_types category and the stone_instances table) have NOT
// been applied to this shared dev DB yet (confirmed: SELECT name FROM
// pgmigrations ... stops at 1714440164000). This migration (1714440167000)
// depends on both. The task's own rule is explicit: never run `migrate
// up`/`down` against the live, shared DB just to get schema applied --
// that would durably alter a database another concurrent session is using.
// So every test below applies ALL THREE migrations' real SQL (generated by
// node-pg-migrate's own MigrationBuilder -- the exact same code path
// `node-pg-migrate up` uses to turn pgm.createTable/addConstraint/sql calls
// into DDL/DML, so this is not a hand-rolled reimplementation) inside the
// one transaction that test runs in, and NEVER commits it.
//
// This migration's up() is a real, DB-WIDE, one-time production conversion:
// it has no WHERE clause scoping it to test data, by design -- it must
// convert every real player's magic weapons. That makes the usual
// zz-prefix-then-DELETE pattern unsafe to use here for the *migration's own*
// SQL: running up() for real against the shared dev DB would create a real
// 'stone_of_<weapon>' catalog row and hand a real, permanent, pre-socketed
// stone to every character in this database that owns a magic weapon --
// including the concurrent human session's characters. That is exactly the
// kind of live-catalog / other-players'-data mutation the project forbids.
//
// So each test below -- fixture setup, up(), assertions, down(), final
// assertions -- runs inside ONE Postgres transaction on a single dedicated
// client, and that transaction is ALWAYS rolled back in `finally`, pass or
// fail. Nothing here is ever committed: up()'s DB-wide SQL still runs for
// real and touches every real magic-weapon owner's row (that is the only way
// to actually prove the migration's SQL, not a mock of it), but none of it
// becomes visible outside this one transaction, and it vanishes on
// ROLLBACK/disconnect with zero residue -- even a hard crash mid-test cannot
// leave anything committed, because COMMIT is never called.
const DB_URL = process.env.TEST_DATABASE_URL
  || process.env.DATABASE_URL
  || 'postgres://user:password@localhost:15432/game_db';

// Builds the real SQL steps for one migration direction via node-pg-migrate's
// own MigrationBuilder (pure, synchronous string generation -- confirmed by
// reading migration-builder.js: no DB access happens until we execute the
// returned strings ourselves) and runs them, in order, on our own
// already-open transaction. Deliberately does NOT use node-pg-migrate's
// `runner`/`Migration.apply`: those inject their own `BEGIN;`/`COMMIT;`
// around each migration (see node-pg-migrate/dist/migration.js `_apply`),
// and since a nested BEGIN on an already-open Postgres session is a no-op
// (with a warning) rather than a real sub-transaction, that COMMIT would
// really commit everything since our own outer BEGIN -- including this
// migration's un-scoped, DB-wide conversion of every real player's magic
// weapons. Building the SQL ourselves and executing it without any
// BEGIN/COMMIT keeps 100% of this test inside the one transaction we
// control and roll back in `finally`.
async function applyMigration(client, migModule, direction) {
  const pgm = new MigrationBuilder({}, {}, false, { debug() {}, info() {}, warn() {}, error() {} });
  const action = migModule[direction];
  action(pgm);
  for (const sql of pgm.getSqlSteps()) {
    await client.query(sql);
  }
}

// SOMET-320. Apply a SETUP migration only if its schema is not already there.
//
// The two migrations below are this file's PREREQUISITE, not its subject: the
// subject is 1714440167000's conversion, applied inside the test bodies and
// left completely untouched by this guard. Applying the prerequisites
// unconditionally works on a virgin database and is impossible on a migrated
// one -- against the dev database every test here died on
//   column "stat_bonus_stat" of relation "item_types" already exists  (42701)
// which, with the sibling stones file, was 12 of the suite's 16 failures.
//
// KEYED ON AN EXPLICIT PRESENCE CHECK, NEVER ON CATCHING THE ERROR -- and in
// THIS file that distinction has teeth, because a duplicate-object error raised
// by the migration under test is a real defect these tests exist to catch.
// Swallowing 42701 here would silently disarm them.
//
// Still correct on a virgin database: the probe reports absent and the
// migration runs as before.
async function applyMigrationIfAbsent(client, migModule, presenceSql) {
  const present = await client.query(presenceSql);
  if (present.rowCount > 0) return false;
  await applyMigration(client, migModule, 'up');
  return true;
}

const HAS_STAT_BONUS_COLUMN = `SELECT 1 FROM information_schema.columns
   WHERE table_name = 'item_types' AND column_name = 'stat_bonus_stat'`;
const HAS_STONE_INSTANCES = `SELECT 1 FROM information_schema.tables
   WHERE table_name = 'stone_instances'`;

// SOMET-320. Serialize with the other files that write item_types' stone rows.
// `node --test` runs files in parallel and three of them touch these rows; two
// doing so in different orders produced an observed "deadlock detected" in a
// full-suite run that passed in isolation. Transaction-scoped, so the ROLLBACK
// in `finally` releases it. See the full rationale in
// migration_stone_item_type_down_guard_db.test.js.
const STONE_CATALOG_LOCK = "SELECT pg_advisory_xact_lock(hashtext('somet320:item_types_stone'))";

async function openTxClient(t) {
  const client = new Client({ connectionString: DB_URL, connectionTimeoutMillis: 3000 });
  try {
    await client.connect();
  } catch (err) {
    const msg = `NO DATABASE at ${DB_URL} (${err.message}) — the magic-weapon conversion migration is UNVERIFIED`;
    if (process.env.CI) assert.fail(msg);
    t.skip(msg);
    return null;
  }
  await client.query('BEGIN');
  await client.query(STONE_CATALOG_LOCK);
  // Bring this transaction's view of the schema up to Task 1 before testing
  // Task 2's conversion migration, which depends on both. Rolled back along
  // with everything else -- the real deploy of Task 1's migrations is a
  // separate, deliberate step, not something a test should do for real.
  //
  // ...or skip them where the database already carries that schema, which is
  // now the normal case: see applyMigrationIfAbsent above.
  await applyMigrationIfAbsent(client, migStoneType, HAS_STAT_BONUS_COLUMN);
  await applyMigrationIfAbsent(client, migStoneInstances, HAS_STONE_INSTANCES);
  return client;
}

// Shared zz-prefixed user/character fixture, all inside the caller's
// transaction.
async function createZzCharacter(client, tag) {
  const user = await client.query(
    `INSERT INTO users (username, password_hash, role) VALUES ($1, 'x', 'player') RETURNING id`,
    [`zz-stones-user-${tag}`],
  );
  const userId = user.rows[0].id;

  const entityType = await client.query(`SELECT id FROM entity_types WHERE name = 'Warrior'`);
  assert.equal(entityType.rowCount, 1, 'setup: the Warrior entity type must exist');

  const character = await client.query(
    `INSERT INTO characters (user_id, slot, name, entity_type_id) VALUES ($1, 1, $2, $3) RETURNING id`,
    [userId, `zz-stones-char-${tag}`, entityType.rows[0].id],
  );
  return character.rows[0].id;
}

async function createZzMagicWeaponType(client, weaponTypeName) {
  const weaponType = await client.query(
    `INSERT INTO item_types (name, category, kind, damage, cooldown, reach, arc_width, element, mana_cost)
     VALUES ($1, 'weapon', 'melee', 12, 0.5, 90, 0.8, 'fire', 10) RETURNING id`,
    [weaponTypeName],
  );
  return weaponType.rows[0].id;
}

async function grantWeaponInstance(client, characterId, weaponTypeId) {
  const item = await client.query(
    `INSERT INTO player_items (id, character_id, item_type_id, quantity)
     VALUES (gen_random_uuid(), $1, $2, 1) RETURNING id`,
    [characterId, weaponTypeId],
  );
  return item.rows[0].id;
}

test('converting existing magic weapons to stones round-trips cleanly through down() (rolled back, never committed)', async (t) => {
  const client = await openTxClient(t);
  if (!client) return;

  const tag = `${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const weaponTypeName = `zz-stones-test-wand-${tag}`;
  const stoneTypeName = `stone_of_${weaponTypeName}`;

  try {
    const characterId = await createZzCharacter(client, tag);
    const weaponTypeId = await createZzMagicWeaponType(client, weaponTypeName);
    const weaponPlayerItemId1 = await grantWeaponInstance(client, characterId, weaponTypeId);

    // A SECOND instance of the SAME magic weapon type on the SAME
    // character -- this is exactly the multi-instance-ownership case the
    // plan flagged as a real correctness risk for a plain
    // (character_id, item_type_id) re-join. The live dev DB had zero such
    // rows when queried (see the migration's header comment), but this test
    // must not depend on that being true forever: it proves the migration
    // is correct BY CONSTRUCTION, not merely correct against today's data.
    const weaponPlayerItemId2 = await grantWeaponInstance(client, characterId, weaponTypeId);

    // Full row snapshot ("byte-identical" means all columns, not a curated
    // subset) -- deepEqual on node:assert correctly compares Date values by
    // getTime(), so created_at is safe to include.
    const before = await client.query(
      'SELECT * FROM player_items WHERE character_id = $1 ORDER BY id',
      [characterId],
    );
    assert.equal(before.rowCount, 2, 'setup: two owned instances of the same magic weapon type before conversion');

    // --- up() ---
    await applyMigration(client, mig, 'up');

    const stoneType = await client.query(
      `SELECT category, element, mana_cost, damage, cooldown, stackable FROM item_types WHERE name = $1`,
      [stoneTypeName],
    );
    assert.equal(stoneType.rowCount, 1, 'up() must create exactly one stone item_type for the weapon type');
    assert.equal(stoneType.rows[0].category, 'stone');
    assert.equal(stoneType.rows[0].element, 'fire', 'the stone must carry the weapon element');
    assert.equal(Number(stoneType.rows[0].mana_cost), 10, 'the stone must carry the weapon mana_cost');
    assert.equal(Number(stoneType.rows[0].damage), 12, 'the stone must carry the weapon damage');
    assert.equal(Number(stoneType.rows[0].cooldown), 0.5, 'the stone must carry the weapon cooldown -- combat (Task 5) reads a socketed spell stone\'s cooldown as authoritative, so a hardcoded 0 here would give every converted weapon a zero-cooldown exploit');
    assert.equal(stoneType.rows[0].stackable, false);

    const stones = await client.query(
      `SELECT si.player_item_id, si.socketed_into_id
         FROM stone_instances si
         JOIN player_items pi ON pi.id = si.player_item_id
        WHERE pi.character_id = $1
        ORDER BY si.socketed_into_id`,
      [characterId],
    );
    assert.equal(stones.rowCount, 2,
      'each of the two weapon instances must get its OWN stone -- the multi-instance case must not collapse to one');
    const socketedInto = stones.rows.map((r) => r.socketed_into_id).sort();
    assert.deepEqual(
      socketedInto, [weaponPlayerItemId1, weaponPlayerItemId2].sort(),
      'each stone must be socketed into a DIFFERENT weapon instance -- no stone double-assigned, none skipped',
    );
    assert.notEqual(
      stones.rows[0].player_item_id, stones.rows[1].player_item_id,
      'the two stones must be distinct player_items rows',
    );

    // --- down() ---
    await applyMigration(client, mig, 'down');

    const after = await client.query(
      'SELECT * FROM player_items WHERE character_id = $1 ORDER BY id',
      [characterId],
    );
    assert.deepEqual(after.rows, before.rows,
      'down() must restore player_items to BYTE-IDENTICAL state (every column, same rows, same order)');

    const stoneTypeGone = await client.query('SELECT id FROM item_types WHERE name = $1', [stoneTypeName]);
    assert.equal(stoneTypeGone.rowCount, 0, 'down() must remove the stone item_type it created');

    const stonesGone = await client.query(
      'SELECT * FROM stone_instances WHERE socketed_into_id IN ($1, $2)',
      [weaponPlayerItemId1, weaponPlayerItemId2],
    );
    assert.equal(stonesGone.rowCount, 0, 'down() must remove the stone_instances rows (cascaded via player_items)');

    const weaponTypeStill = await client.query('SELECT id FROM item_types WHERE id = $1', [weaponTypeId]);
    assert.equal(weaponTypeStill.rowCount, 1, "down() must NOT touch the weapon's own item_type row");
  } finally {
    // ALWAYS rollback, pass or fail. Nothing in this test is ever committed.
    await client.query('ROLLBACK').catch(() => {});
    await client.end().catch(() => {});
  }
});

// CRITICAL FIX REGRESSION (review finding): a pre-existing item_types row
// already named 'stone_of_<weapon>' but NOT category='stone' (e.g. an
// admin-authored consumable that happens to collide) must not be treated as
// the weapon's stone. Before the fix, `targets` joined on name alone, so
// this decoy row would have been paired with the weapon and granted to the
// player as if it were a real stone. Reproduces the reviewer's exact repro.
test('a pre-existing NON-STONE item_type sharing the stone_of_<weapon> name is never mistaken for the real stone', async (t) => {
  const client = await openTxClient(t);
  if (!client) return;

  const tag = `${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const weaponTypeName = `zz-stones-collide-wand-${tag}`;
  const decoyName = `stone_of_${weaponTypeName}`;

  try {
    const characterId = await createZzCharacter(client, tag);
    const weaponTypeId = await createZzMagicWeaponType(client, weaponTypeName);
    const weaponPlayerItemId = await grantWeaponInstance(client, characterId, weaponTypeId);

    // The decoy: same name the migration will try to create/use, wrong
    // category. A real, unrelated, pre-existing catalog item.
    const decoy = await client.query(
      `INSERT INTO item_types (name, category, damage, cooldown, stackable)
       VALUES ($1, 'consumable', 0, 0, true) RETURNING id`,
      [decoyName],
    );
    const decoyTypeId = decoy.rows[0].id;

    const before = await client.query(
      'SELECT * FROM player_items WHERE character_id = $1 ORDER BY id',
      [characterId],
    );
    assert.equal(before.rowCount, 1, 'setup: one owned weapon instance, no items yet, before conversion');

    // --- up() ---
    await applyMigration(client, mig, 'up');

    // The catalog insert must have no-op'd on the name collision -- no
    // SECOND row named decoyName, and critically the EXISTING decoy row is
    // untouched (still category='consumable').
    const sameName = await client.query('SELECT id, category FROM item_types WHERE name = $1', [decoyName]);
    assert.equal(sameName.rowCount, 1, 'the name collision must not produce a second catalog row');
    assert.equal(sameName.rows[0].id, decoyTypeId, 'the pre-existing decoy row must be the one that remains');
    assert.equal(sameName.rows[0].category, 'consumable', 'the decoy row must be untouched by the catalog insert');

    // The weapon must NOT have been granted the decoy item, and must not
    // have gained ANY player_items row -- with no real stone type available
    // (the real one couldn't be created due to the name collision), the
    // correct, safe behavior is to skip this weapon type entirely, not
    // substitute the decoy.
    const granted = await client.query(
      'SELECT * FROM player_items WHERE character_id = $1 AND item_type_id = $2',
      [characterId, decoyTypeId],
    );
    assert.equal(granted.rowCount, 0, 'the decoy item must NEVER be granted to the player');

    const stoneInstances = await client.query(
      'SELECT * FROM stone_instances WHERE socketed_into_id = $1',
      [weaponPlayerItemId],
    );
    assert.equal(stoneInstances.rowCount, 0, 'no stone_instances row may point at the decoy or anything else');

    const afterUp = await client.query(
      'SELECT * FROM player_items WHERE character_id = $1 ORDER BY id',
      [characterId],
    );
    assert.deepEqual(afterUp.rows, before.rows,
      'the character\'s player_items must be UNCHANGED by up() when the real stone type could not be created');

    // --- down() ---
    await applyMigration(client, mig, 'down');

    const afterDown = await client.query(
      'SELECT * FROM player_items WHERE character_id = $1 ORDER BY id',
      [characterId],
    );
    assert.deepEqual(afterDown.rows, before.rows, 'down() must also leave player_items unchanged in this scenario');

    const decoyStill = await client.query('SELECT id, category FROM item_types WHERE id = $1', [decoyTypeId]);
    assert.equal(decoyStill.rowCount, 1, "down() must NOT delete the decoy row -- it isn't category='stone'");
    assert.equal(decoyStill.rows[0].category, 'consumable');
  } finally {
    await client.query('ROLLBACK').catch(() => {});
    await client.end().catch(() => {});
  }
});

// IMPORTANT FIX REGRESSION (review finding): the NOT EXISTS guard added to
// `targets` must make an immediate re-run (nothing unsocketed) a safe
// no-op, not a repeat of the loud unique-index failure the original header
// comment claimed was the only possible outcome.
test('running up() a second time, with nothing unsocketed, is a safe no-op (does not duplicate or error)', async (t) => {
  const client = await openTxClient(t);
  if (!client) return;

  const tag = `${process.pid}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const weaponTypeName = `zz-stones-rerun-wand-${tag}`;

  try {
    const characterId = await createZzCharacter(client, tag);
    const weaponTypeId = await createZzMagicWeaponType(client, weaponTypeName);
    const weaponPlayerItemId = await grantWeaponInstance(client, characterId, weaponTypeId);

    await applyMigration(client, mig, 'up');
    const firstRun = await client.query(
      'SELECT * FROM stone_instances WHERE socketed_into_id = $1', [weaponPlayerItemId],
    );
    assert.equal(firstRun.rowCount, 1, 'setup: the first run grants exactly one stone');

    // Second run, nothing unsocketed in between -- must not throw and must
    // not create a second stone for this weapon.
    await assert.doesNotReject(() => applyMigration(client, mig, 'up'));

    const secondRun = await client.query(
      'SELECT * FROM stone_instances WHERE socketed_into_id = $1', [weaponPlayerItemId],
    );
    assert.equal(secondRun.rowCount, 1, 'a second up() run must not grant a second stone to an already-socketed weapon');
    assert.equal(secondRun.rows[0].player_item_id, firstRun.rows[0].player_item_id,
      'the socketed stone must be the SAME row as the first run created, not a replacement');
  } finally {
    await client.query('ROLLBACK').catch(() => {});
    await client.end().catch(() => {});
  }
});
